- xtask/src/command/dist.rs
Fix: https://github.com/tombi-toml/tombi/issues/172
> fix: windows bin path.

- crates/formatter/src/format/comment.rs
Refactor the test case to use a more relevant example with dependencies, improving clarity and relevance of the test.
> chore: update test case for dangling comments format

- TODO.ja.md
- Mark serde-tombi implementation as completed
- Add cargo.toml special features to the upcoming tasks
> doc: update milestone 4 tasks in TODO.ja.md

- Cargo.lock
- crates/tombi-extension/Cargo.toml
- crates/tombi-extension/src/definition.rs
- crates/tombi-extension/src/lib.rs
- crates/tombi-server/src/handler/goto_declaration.rs
- crates/tombi-server/src/handler/goto_definition.rs
- extensions/tombi-cargo-extension/src/goto_declaration.rs
- extensions/tombi-cargo-extension/src/goto_definition.rs
- extensions/tombi-cargo-extension/src/lib.rs
- extensions/tombi-uv-extension/src/goto_declaration.rs
- extensions/tombi-uv-extension/src/goto_definition.rs
- extensions/tombi-uv-extension/src/lib.rs
- Introduced `DefinitionLocation` and `DefinitionLocations` structs for better handling of definition responses.
- Updated `goto_definition` and `goto_declaration` functions across multiple extensions to utilize the new location types.
- Enhanced Cargo.toml and other related files to include necessary dependencies.
> feat: add definition location handling and update extensions

- docs/src/routes/docs/index.mdx
- editors/zed/extension.toml
Updated the extension name to include "TOML Toolkit" for better identification.
> feat: update extension name for clarity

- extensions/tombi-cargo-extension/src/lib.rs
Updated the logic for retrieving crate locations to handle multiple types of dependencies (dependencies, dev-dependencies, build-dependencies) more efficiently. This change enhances the clarity and maintainability of the code.
> fix: dependency key handling

- docs/src/routes/docs/configuration/index.mdx
Added options for goto-declaration, goto-definition, and goto-type-definition in the configuration documentation.
> feat: enable goto features in configuration

- crates/tombi-diagnostic/src/lib.rs
- crates/tombi-server/src/handler/diagnostic.rs
Updated the Diagnostic struct to derive the Hash trait for improved functionality. Enhanced diagnostic handling by ensuring unique diagnostics in the server's response.
> refactor: add Hash trait to Diagnostic struct

- .github/workflows/ci_rust.yml
- Added caching for dependencies to improve build times.
- Set environment variables for incremental builds and retry limits.
> ci: enhance CI configuration for Rust builds

- crates/tombi-lsp/src/completion.rs
- crates/tombi-lsp/src/completion/completion_content.rs
- crates/tombi-lsp/src/completion/value/boolean.rs
- crates/tombi-lsp/src/completion/value/float.rs
- crates/tombi-lsp/src/completion/value/integer.rs
- crates/tombi-lsp/src/completion/value/local_date.rs
- crates/tombi-lsp/src/completion/value/local_date_time.rs
- crates/tombi-lsp/src/completion/value/local_time.rs
- crates/tombi-lsp/src/completion/value/offset_date_time.rs
- crates/tombi-lsp/src/completion/value/string.rs
- crates/tombi-lsp/src/completion/value/table.rs
- crates/tombi-schema-store/src/schema/table_schema.rs
Enhance completion item functionality by including a deprecated field in various schema implementations, improving the clarity of deprecated items in the completion suggestions.
> feat: add deprecated field to completion items

- extensions/tombi-cargo-extension/src/document_link.rs
- Added support for retrieving subcrate Cargo.toml paths.
- Updated document link generation to include subcrate information.
- Improved handling of workspace and dependency links.
> feat: enhance document link functionality for subcrates

- docs/src/components/Sidebar.tsx
Adjusted the Sidebar component's navigation class to ensure it displays correctly on medium-sized screens and above.
> style: update Sidebar component for responsive design

- docs/public/install.sh
Changed the shebang from bash to sh and updated conditional checks to use POSIX-compliant syntax. Enhanced output formatting for better readability.
> style: update install script for improved compatibility

- rust/tombi-cli/src/app.rs
This PR optimizes the Tokio runtime initialization by reducing overhead from `tracing_subscriber`.
The function `tracing_subscriber::EnvFilter::from` performs expensive parsing to allow for diverse filter specifications. However, our use case only involves very simple filter values such as `INFO` or `TRACE`. Thus, this parsing overhead is unnecessary.
By directly converting the enum returned by `args.verbose.log_level_filter()` into `tracing_subscriber::filter::LevelFilter` and passing that instead, we can achieve roughly a 1ms improvement in performance. On my machine, the execution time of `tombo format --offline` improved from approximately 4.7ms to 3.7ms.
> perf(cli): optimize tracing_subscriber initialization

- crates/tombi-lsp/src/backend.rs
- crates/tombi-lsp/src/handler/initialized.rs
- crates/tombi-schema-store/src/store.rs
- rust/serde_tombi/src/ser.rs
Fix: https://github.com/tombi-toml/tombi/issues/354
> Fix schema loading

- crates/tombi-config/src/schema.rs
- crates/tombi-diagnostic/src/lib.rs
- crates/tombi-document-tree/src/error.rs
- crates/tombi-linter/src/error.rs
- crates/tombi-linter/src/lib.rs
- crates/tombi-linter/src/warning.rs
- crates/tombi-lsp/src/completion/value/table.rs
- crates/tombi-lsp/tests/completion_labels.rs
- crates/tombi-parser/src/error.rs
- crates/tombi-schema-store/src/schema/referable_schema.rs
- crates/tombi-schema-store/src/schema/value_schema.rs
- crates/tombi-schema-store/src/store.rs
- crates/tombi-validator/src/error.rs
- crates/tombi-validator/src/validate/any_of.rs
- crates/tombi-validator/src/validate/array.rs
- crates/tombi-validator/src/validate/one_of.rs
- crates/tombi-validator/src/validate/table.rs
- crates/tombi-validator/src/warning.rs
- docs/src/routes/docs/configuration/index.mdx
- rust/serde_tombi/src/de.rs
- tombi.schema.json
- tombi.toml
use 'root' instead of 'root-keys'
> feat: Change subschema

- crates/tombi-config/src/lint.rs
- tombi.schema.json
- Added documentation for LintOptions and LintRules in the code.
- Updated the JSON schema to include titles and descriptions for lint rules.
> feat: add lint rules documentation in schema and struct

- Cargo.toml
- editors/vscode/package.json
- python/tombi-beta/pyproject.toml
Updated author name and email from 'y7010' to 'yn7010' in Cargo.toml, package.json, and pyproject.toml files.
> chore: update author information in project files

- Cargo.toml
- editors/vscode/package.json
- python/tombi-beta/pyproject.toml
Corrected the author name from 'yn7010' to 'ya7010' in Cargo.toml, package.json, and pyproject.toml for consistency.
> fix: update author name in configuration files

- Cargo.lock
- Cargo.toml
- DEVELOPMENT.md
- editors/vscode/package.json
- extensions/tombi-extension-cargo/Cargo.toml
- extensions/tombi-extension-uv/Cargo.toml
- package.json
- pyproject.toml
- typescript/tombi/package.json
- xtask/src/command/set_version.rs
fix: https://github.com/tombi-toml/tombi/issues/452
> Change dev version

- crates/tombi-lsp/src/completion/value/array.rs
- crates/tombi-lsp/tests/completion_labels.rs
Added logic to include default values in completion items for ArraySchema. This enhancement improves user experience by providing suggested default values when applicable.
> feat: enhance completion items with default values

- .github/workflows/ci_python.yml
Updated the CI Python workflow to remove redundant installation and synchronization steps, ensuring a more efficient process while maintaining functionality.
> ci: streamline CI workflow by removing unnecessary steps

- Cargo.lock
- crates/tombi-json-arena/Cargo.toml
- crates/tombi-json-arena/README.md
- crates/tombi-json-arena/src/arena.rs
- crates/tombi-json-arena/src/arena/string.rs
- crates/tombi-json-arena/src/arena/value.rs
- crates/tombi-json-arena/src/lib.rs
- Introduced the tombi-json-arena crate for optimized JSON parsing.
- Added modules for string and value arenas.
- Implemented StrArena and ValueArena with allocation and retrieval methods.
- Updated README with project description.
> feat: add tombi-json-arena crate with initial implementation

- schemas/cargo.schema.json
latest https://www.schemastore.org/cargo.json adds an "inherits" definition.
> fix: Update cargo schema

- Cargo.lock
- Cargo.toml
- crates/tombi-config/src/lib.rs
- rust/serde_tombi/Cargo.toml
- rust/serde_tombi/src/config.rs
- schemas/catalog.json
Support: https://github.com/tombi-toml/tombi/issues/555
> feat: support user config.

- crates/tombi-config/src/lint.rs
- crates/tombi-extension/src/completion.rs
- crates/tombi-linter/src/lib.rs
- crates/tombi-lsp/src/completion.rs
- crates/tombi-lsp/src/completion/value/all_of.rs
- crates/tombi-lsp/src/completion/value/any_of.rs
- crates/tombi-lsp/src/completion/value/one_of.rs
- crates/tombi-validator/src/error.rs
- crates/tombi-validator/src/validate/boolean.rs
- crates/tombi-validator/src/validate/float.rs
- crates/tombi-validator/src/validate/integer.rs
- crates/tombi-validator/src/validate/local_date.rs
- crates/tombi-validator/src/validate/local_date_time.rs
- crates/tombi-validator/src/validate/local_time.rs
- crates/tombi-validator/src/validate/offset_date_time.rs
- crates/tombi-validator/src/validate/string.rs
- schemas/tombi.schema.json
Support: https://github.com/tombi-toml/tombi/issues/574
> feat: update the enum title on the completion hint

- crates/tombi-config/src/types/line_ending.rs
- crates/tombi-formatter/src/formatter.rs
- crates/tombi-lsp/src/handler/formatting.rs
Support: https://github.com/tombi-toml/tombi/issues/588
> Support text diff

- Cargo.lock
- Cargo.toml
- rust/tombi-cli/Cargo.toml
- rust/tombi-cli/src/app/arg/file.rs
- Integrated the rayon crate to enhance file processing performance through parallel execution.
- Updated Cargo.toml and Cargo.lock to include rayon and its dependencies.
- Refactored file handling logic to utilize parallel iterators for improved efficiency.
> feat: add rayon for parallel processing in file handling

- schemas/cargo.schema.json
Added an 'inherits' property reference to the cargo schema to enhance configuration capabilities.
> feat: add inherits property to cargo schema

- crates/tombi-linter/src/lib.rs
- crates/tombi-lsp/tests/test_completion_labels.rs
- crates/tombi-validator/src/validate/array.rs
- crates/tombi-validator/src/validate/table.rs
- crates/tombi-validator/src/warning.rs
- schemas/tombi.schema.json
- schemas/type-test.schema.json
- type-test.toml
- xtask/src/command/codegen_jsonschema.rs
Suppot https://github.com/tombi-toml/tombi/issues/618
> chore: update document message.

- crates/tombi-lsp/src/completion/value/string.rs
fix: https://github.com/tombi-toml/tombi/issues/716
> fix: completion bug.

- .github/workflows/ci_intellij_plugin.yml
Part of #744.
I'm not sure if this actually works or not. Only by merging can we know.
> feat: Upload IntelliJ plugin artifact to JetBrains Marketplace on push

- crates/tombi-schema-store/src/schema/value_schema.rs
fix: https://github.com/tombi-toml/tombi/issues/759
📝  Looking at the JSON Schema [examples](https://json-schema.org/understanding-json-schema/reference/enum), schemas with only enums and no specified types are allowed.
> feat: support enum only schema.

- crates/tombi-lsp/tests/test_completion_labels.rs
- crates/tombi-schema-store/src/store.rs
- crates/tombi-test-lib/src/path.rs
- schemas/untagged-union.schema.json
fix: https://github.com/tombi-toml/tombi/issues/804
> Refactor schema store

- Cargo.lock
- Cargo.toml
- crates/tombi-lsp/src/hover/constraints.rs
- crates/tombi-lsp/src/hover/value/string.rs
- crates/tombi-schema-store/src/schema/all_of_schema.rs
- crates/tombi-schema-store/src/schema/any_of_schema.rs
- crates/tombi-schema-store/src/schema/array_schema.rs
- crates/tombi-schema-store/src/schema/document_schema.rs
- crates/tombi-schema-store/src/schema/one_of_schema.rs
- crates/tombi-schema-store/src/schema/referable_schema.rs
- crates/tombi-schema-store/src/schema/string_schema.rs
- crates/tombi-schema-store/src/schema/table_schema.rs
- crates/tombi-schema-store/src/schema/value_schema.rs
- crates/tombi-validator/Cargo.toml
- crates/tombi-validator/src/error.rs
- crates/tombi-validator/src/validate.rs
- crates/tombi-validator/src/validate/format.rs
- crates/tombi-validator/src/validate/format/email.rs
- crates/tombi-validator/src/validate/format/hostname.rs
- crates/tombi-validator/src/validate/format/uri.rs
- crates/tombi-validator/src/validate/format/uuid.rs
- crates/tombi-validator/src/validate/string.rs
- crates/tombi-x-keyword/src/lib.rs
- docs/src/routes/docs/json-schema.mdx
- json.schemastore.org/pyproject.json
- pyproject.toml
Support: https://github.com/tombi-toml/tombi/issues/808
> Support x tombi string formats

- crates/tombi-glob/src/walk_dir.rs
fix: https://github.com/tombi-toml/tombi/issues/834
> fix: disable hiddlen options.

- pyproject.toml
Fix: https://github.com/tombi-toml/tombi/issues/967
> fix: dependencies.

- Cargo.lock
- rust/tombi-cli/Cargo.toml
- rust/tombi-cli/src/app.rs
- rust/tombi-cli/src/app/command.rs
- rust/tombi-cli/src/app/command/completion.rs
Example:
```sh
tombi completion fish > tombi.fish
```
Closes #1010
> feat(cli): Add `completion` subcommand

- crates/tombi-text/src/position.rs
fix: https://github.com/tombi-toml/tombi/issues/1015
The cause will be addressed later.
> fix: text position.

- json.schemastore.org/cargo.json
support: https://github.com/tombi-toml/tombi/issues/1024
> feat: add "check-cfg" properties.

- crates/tombi-linter/src/lib.rs
- crates/tombi-linter/src/linter.rs
- crates/tombi-lsp/src/completion/schema_completion.rs
- crates/tombi-lsp/src/hover/any_of.rs
- crates/tombi-lsp/src/hover/one_of.rs
- crates/tombi-validator/src/error.rs
- crates/tombi-validator/src/lib.rs
- crates/tombi-validator/src/validate.rs
- crates/tombi-validator/src/validate/all_of.rs
- crates/tombi-validator/src/validate/any_of.rs
- crates/tombi-validator/src/validate/array.rs
- crates/tombi-validator/src/validate/boolean.rs
- crates/tombi-validator/src/validate/float.rs
- crates/tombi-validator/src/validate/integer.rs
- crates/tombi-validator/src/validate/local_date.rs
- crates/tombi-validator/src/validate/local_date_time.rs
- crates/tombi-validator/src/validate/local_time.rs
- crates/tombi-validator/src/validate/offset_date_time.rs
- crates/tombi-validator/src/validate/one_of.rs
- crates/tombi-validator/src/validate/string.rs
- crates/tombi-validator/src/validate/table.rs
- crates/tombi-validator/src/validate/value.rs
Support: https://github.com/tombi-toml/tombi/issues/1029
> feat: diagnostic filter.

- crates/tombi-extension/src/completion.rs
- crates/tombi-lsp/src/completion/value/table.rs
- crates/tombi-lsp/tests/test_completion_labels.rs
- crates/tombi-schema-store/src/schema/table_schema.rs
- crates/tombi-x-keyword/src/lib.rs
- json.schemastore.org/cargo.json
- json.schemastore.org/pyproject.json
> feat: add x-tombi-additional-key-label features.

- crates/tombi-lsp/src/handler/formatting.rs
With multiple newlines at the end of a document the LSP formatter is leaving an extra final newline instead of leaving just a single final newline.
This is due to the compute_text_edits using incorrect position when calculating where the end of the document is when it ends with a newline.
The fix is to use the last line of the old text if the new text finishes with a newline.
Issue: https://github.com/tombi-toml/tombi/issues/934
> fix(lsp): formatting should trim extra final newline

- crates/tombi-lsp/src/handler/document_symbol.rs
> fix: document symbol.
