crates/server/src/hover/value/table.rs, crates/server/tests/hover.rs
- Introduced a new test case for handling the 'test-command' key in the 'tool.cibuildwheel.overrides' section of the pyproject.toml.
- Updated tracing logs for better debugging of hover content.
=> test: add test for pyproject_tool_cibuildwheel overrides

.github/workflows/release_cli_vscode.yml, .github/workflows/release_python.yml, .github/workflows/toml-test.yml
Add continue-on-error: true to multiple workflow jobs to ensure that the workflows continue executing even if some steps fail.
=> ci: add continue-on-error to workflow jobs

Cargo.lock, crates/formatter/src/formatter.rs, crates/linter/src/linter.rs, crates/parser/src/lib.rs, rust/serde_tombi/Cargo.toml, rust/serde_tombi/src/document.rs
- Introduced a new `parsed_and_ast` function in the parser module to encapsulate the parsing and AST generation logic.
- Updated the formatter and linter to utilize the new parsing function, improving code clarity and reducing duplication.
- Removed the `format_without_schema` method from the formatter, streamlining the formatting process.
=> refactor: simplify parsing and formatting logic

docs/src/routes/docs/formatter/treatment-of-comments.mdx
Enhanced the documentation on comment handling in Tombi, refining language for clarity and consistency. Adjusted terminology and examples to better explain the treatment of leading, trailing, and dangling comments.
=> docs: improve clarity and consistency in comment treatment section

crates/formatter/src/format/value/date_time.rs
Add a test case to ensure pico seconds are retained in local time formatting.
=> test: add test for pico seconds retention

rust/serde_tombi/src/lib.rs
Refactor the serialization logic to use a new `CargoToml` struct that includes package details and dependencies, replacing the previous `Config` structure. This enhances the clarity and functionality of the serialization process.
=> feat: update serialization structure for Cargo.toml

crates/server/src/backend.rs, crates/server/src/handler/completion.rs, crates/server/src/handler/diagnostic.rs, crates/server/src/handler/document_link.rs, crates/server/src/handler/document_symbol.rs, crates/server/src/handler/folding_range.rs, crates/server/src/handler/formatting.rs, crates/server/src/handler/get_toml_version.rs, crates/server/src/handler/hover.rs, crates/server/src/handler/semantic_tokens_full.rs
Updated the backend to provide TOML version based on the document's schema or configuration. This change improves the handling of TOML versioning in various document-related operations.
=> feat: enhance TOML version retrieval from documents

docs/src/routes/docs/index.mdx
Updated the documentation to specify 'pyproject.toml' and 'Cargo.toml' for better clarity on TOML usage in modern development tools.
=> docs: clarify TOML references in documentation

.cursor/rules/rust-code.mdc, crates/server/tests/goto_type_definition.rs
- Introduced new tests for the goto type definition feature covering TOML schemas including tombi, cargo, and pyproject.
- Updated rust-code rules to disallow mod.rs usage.
=> test: add goto type definition tests for TOML schemas

Cargo.lock, crates/tombi-json-value/Cargo.toml, crates/tombi-json-value/src/lib.rs
This commit introduces the tombi-json-value crate, which defines an enum for representing various JSON value types, including null, boolean, number, string, array, and object. It also includes methods for type checking and conversion to/from different types, along with serialization and deserialization support using Serde.
=> feat: add tombi-json-value crate for JSON value representation

.github/workflows/release_cli_vscode.yml
Updated the CI workflow to use Ubuntu 24.04 for all relevant jobs to ensure compatibility with the latest dependencies and features.
=> ci: update Ubuntu version in CI workflow

crates/tombi-diagnostic/examples/diagnostics.rs, crates/tombi-formatter/tests/x_tombi_order.rs, crates/tombi-linter/src/lib.rs, crates/tombi-schema-store/tests/test_tombi_schema.rs, crates/tombi-server/tests/goto_definition.rs, crates/tombi-server/tests/goto_type_definition.rs, crates/tombi-test-lib/src/path.rs, rust/serde_tombi/src/de.rs, xtask/src/command/codegen_grammar.rs, xtask/src/command/codegen_jsonschema.rs, xtask/src/command/dist.rs, xtask/src/command/set_version.rs, xtask/src/command/toml_test.rs, xtask/src/utils.rs
Updated all references from `project_root` to `project_root_path` for consistency and clarity across the codebase.
=> refactor: test_code

Cargo.lock, Cargo.toml, editors/zed/.gitignore, editors/zed/Cargo.toml, editors/zed/extension.toml, editors/zed/languages/toml/brackets.scm, editors/zed/languages/toml/config.toml, editors/zed/languages/toml/highlights.scm, editors/zed/languages/toml/outline.scm, editors/zed/languages/toml/overrides.scm, editors/zed/languages/toml/redactions.scm, editors/zed/languages/toml/textobjects.scm, editors/zed/src/lib.rs, rust/serde_tombi/src/de.rs, sample.toml, tombi.toml
Support https://github.com/tombi-toml/tombi/issues/171
- Introduced new grammar, highlighting, and configuration files for TOML language support in the Zed editor.
- Added necessary dependencies and updated workspace configuration.
- Included .gitignore for editor-specific files.
=> feat: add TOML language support for Zed editor

crates/tombi-ast-editor/Cargo.toml, crates/tombi-ast/Cargo.toml, crates/tombi-config/Cargo.toml, crates/tombi-date-time/Cargo.toml, crates/tombi-diagnostic/Cargo.toml, crates/tombi-document-tree/Cargo.toml, crates/tombi-document/Cargo.toml, crates/tombi-extension/Cargo.toml, crates/tombi-formatter/Cargo.toml, crates/tombi-json-lexer/Cargo.toml, crates/tombi-json-syntax/Cargo.toml, crates/tombi-json-value/Cargo.toml, crates/tombi-json/Cargo.toml, crates/tombi-lexer/Cargo.toml, crates/tombi-linter/Cargo.toml, crates/tombi-parser/Cargo.toml, crates/tombi-rg-tree/Cargo.toml, crates/tombi-schema-store/Cargo.toml, crates/tombi-server/Cargo.toml, crates/tombi-syntax/Cargo.toml, crates/tombi-toml-text/Cargo.toml, crates/tombi-validator/Cargo.toml, editors/zed/Cargo.toml, extensions/tombi-cargo-extension/Cargo.toml, extensions/tombi-uv-extension/Cargo.toml, rust/serde_tombi/Cargo.toml, rust/tombi-cli/Cargo.toml, toml-test/Cargo.toml, xtask/Cargo.toml
Refactor all Cargo.toml files to replace the old dependency syntax with the new workspace syntax for better consistency and clarity.
=> chore: update Cargo.toml dependencies to use workspace syntax

Cargo.lock, Cargo.toml, editors/zed/Cargo.toml, editors/zed/extension.toml, editors/zed/src/lib.rs
Updated the asset naming logic to strip the prefix from the release version and improved the format for version directories. This enhances clarity and consistency in the generated asset names.
=> fix: zed tombi extension.

Cargo.lock, crates/tombi-document/src/value/float.rs, crates/tombi-formatter/src/format/value/array.rs, crates/tombi-json-value/Cargo.toml, crates/tombi-json-value/src/macros.rs, crates/tombi-json/Cargo.toml, crates/tombi-json/src/lib.rs, crates/tombi-json/src/parser.rs, crates/tombi-rg-tree/Cargo.toml, crates/tombi-rg-tree/src/green/builder.rs, crates/tombi-rg-tree/src/red/node.rs, crates/tombi-rg-tree/src/syntax_text.rs, crates/tombi-schema-store/src/schema/schema_accessor.rs, crates/tombi-server/src/hover.rs, crates/tombi-text/Cargo.toml, crates/tombi-text/src/range.rs, crates/tombi-text/src/relative_position.rs, rust/serde_tombi/src/de.rs, rust/tombi-cli/src/app/command/format.rs, rust/tombi-cli/src/app/command/lint.rs
This commit adds the `pretty_assertions` crate to the dev-dependencies of multiple Cargo.toml files to enhance test output readability. Additionally, it updates assertions to use `pretty_assertions` for better comparison output in tests.
=> chore: add pretty_assertions to dev-dependencies

crates/tombi-config/src/types/schema_catalog_path.rs, crates/tombi-extension/src/definition.rs, crates/tombi-json-lexer/src/cursor.rs, crates/tombi-json-value/src/lib.rs, crates/tombi-json-value/src/number.rs, crates/tombi-json/src/lib.rs, crates/tombi-schema-store/src/store.rs, crates/tombi-server/src/backend.rs, crates/tombi-server/src/handler/goto_type_definition.rs, docs/public/install.sh, extensions/tombi-cargo-extension/src/lib.rs, extensions/tombi-uv-extension/src/goto_declaration.rs, extensions/tombi-uv-extension/src/lib.rs, rust/serde_tombi/src/de.rs, rust/serde_tombi/src/ser.rs
- Added Default implementations for SchemaStore and Deserializer structs to simplify instantiation.
- Updated related code to utilize the new Default trait where applicable.
=> refactor: implement Default trait for SchemaStore and Deserializer

crates/tombi-config/src/lib.rs, crates/tombi-config/src/server.rs, crates/tombi-server/src/handler/completion.rs, crates/tombi-server/src/handler/diagnostic.rs, crates/tombi-server/src/handler/formatting.rs, crates/tombi-server/src/handler/goto_declaration.rs, crates/tombi-server/src/handler/goto_definition.rs, crates/tombi-server/src/handler/goto_type_definition.rs, crates/tombi-server/src/handler/hover.rs, crates/tombi-server/tests/completion_edit.rs, crates/tombi-server/tests/completion_labels.rs, docs/src/routes/docs/configuration/index.mdx, rust/serde_tombi/src/de.rs, tombi.schema.json, tombi.toml
Updated configuration and handler files to replace 'server' references with 'lsp' for improved clarity and consistency in the codebase.
=> feat: rename [server] to [lsp] in configuration and handlers

crates/tombi-lsp/tests/folding_range.rs
Added a set of tests to validate folding range functionality for various TOML document structures, including simple tables, multiple tables, and arrays of tables.
=> test: add folding range tests for TOML documents

crates/tombi-lsp/tests/folding_range.rs
Reorganized the expected folding ranges in various tests for clarity and consistency. Added sorting to the actual results for improved comparison.
=> test: reorder expected ranges in folding range tests

crates/tombi-diagnostic/examples/diagnostics.rs, crates/tombi-diagnostic/src/printer.rs, crates/tombi-diagnostic/src/printer/pretty.rs, crates/tombi-diagnostic/src/printer/simple.rs, rust/tombi-cli/src/app/command/format.rs, rust/tombi-cli/src/app/command/lint.rs, rust/tombi-cli/src/error.rs
Change `diagnostic::Print` to require `&mut`, removing the need for `Copy`.
The current design, which requires the `Copy` trait, is sufficient for implementations that write exclusively to stdout.
However, this approach makes it impossible to implement a printer that internally buffers outputs for later retrieval.
(I am developing a plugin for a tool that integrates with tombi, which requires this functionality.)
This PR changes the API to use `&mut` references for writing, thereby removing the requirement for `Copy`. For parallel implementations involving multiple threads, a `Clone` trait is required instead.
=> refactor: prevent the printer from requesting a Copy and make it use &mut

crates/tombi-ast-editor/src/node.rs, crates/tombi-document/src/lib.rs, crates/tombi-formatter/src/format/value/array.rs, crates/tombi-formatter/src/formatter.rs, crates/tombi-linter/src/linter.rs, crates/tombi-lsp/src/backend.rs, crates/tombi-parser/src/lib.rs, crates/tombi-parser/src/parse/root.rs, extensions/tombi-cargo-extension/src/lib.rs, extensions/tombi-uv-extension/src/lib.rs, rust/serde_tombi/src/config.rs, rust/serde_tombi/src/de.rs, toml-test/bin/decode.rs
Updated parsing functions to directly use toml_version instead of wrapping it in an Option. This simplifies the code and improves clarity across multiple modules.
=> refactor: remove unnecessary option wrapping for toml_version

.github/workflows/release_python.yml, Cargo.lock, crates/tombi-ast-editor/Cargo.toml, crates/tombi-date-time/Cargo.toml, crates/tombi-extension/Cargo.toml, crates/tombi-json-lexer/Cargo.toml, crates/tombi-json-syntax/Cargo.toml, crates/tombi-json-value/Cargo.toml, crates/tombi-json/Cargo.toml, crates/tombi-lexer/Cargo.toml, crates/tombi-linter/Cargo.toml, crates/tombi-schema-store/Cargo.toml, crates/tombi-toml-text/Cargo.toml, crates/tombi-validator/Cargo.toml, extensions/tombi-cargo-extension/Cargo.toml, extensions/tombi-uv-extension/Cargo.toml, rust/serde_tombi/Cargo.toml
Set all package versions to 0.0.0 in Cargo.toml files and adjust GitHub Actions workflow to remove unnecessary output redirection.
=> chore: update package versions to 0.0.0

docs/src/routes/docs/installation.mdx
Added a new installation command using 'uvx' for easier setup of tombi in the documentation.
=> docs: add alternative installation command for tombi

docs/src/routes/docs/json-schema.mdx
Replaced the plain text reference to the JSON Schema Store with a formatted link for better accessibility and clarity in the documentation.
=> docs: update link to JSON Schema Store in documentation

.github/workflows/release_npm.yml, typescript/tombi/package.json
This change allows manual triggering of the NPM release workflow in addition to the existing tag-based triggers.
=> ci: add workflow_dispatch trigger for NPM release workflow

.github/workflows/release_npm.yml
Replaced npm commands with pnpm for dependency installation and publishing in the release workflow. Updated Node.js setup to use a version file and added caching for pnpm.
=> ci: update NPM release workflow to use pnpm

.github/workflows/release_cli_vscode.yml, .github/workflows/release_pypi.yml
Updated the release workflows to eliminate the continue-on-error setting, ensuring that failures are properly reported and handled.
=> ci: remove continue-on-error from workflows

crates/tombi-config/src/schema.rs, docs/src/routes/docs/configuration/index.mdx, tombi.schema.json, tombi.toml
- Introduced a new optional `root` field in the SubSchema struct to allow specifying accessors for applying the sub schema.
- Updated related documentation and schema files to reflect this change.
=> feat: add root accessor to SubSchema for enhanced flexibility

crates/tombi-extension/src/definition.rs, extensions/tombi-extension-cargo/src/lib.rs, extensions/tombi-extension-uv/src/lib.rs
Updated DefinitionLocation instantiation to use struct initialization instead of a constructor for improved clarity and consistency across the codebase.
=> refactor: replace constructor with struct initialization for DefinitionLocation

crates/tombi-config/src/lint.rs, tombi.schema.json
Updated the LintRules struct to use SeverityLevelDefault types instead of WarnSeverityLevel. Adjusted references in the schema to reflect these changes.
=> refactor: update severity levels in lint rules and schema

docs/src/components/CodeTabs.tsx, docs/src/routes/docs/installation.mdx
Introduces a new CodeTabs component to enhance documentation by allowing users to switch between different installation commands for various package managers. This improves usability and clarity in the installation instructions.
=> docs: add CodeTabs component for command display

crates/tombi-lsp/src/completion.rs, crates/tombi-lsp/src/completion/comment.rs, crates/tombi-lsp/src/completion/completion_edit.rs, crates/tombi-lsp/src/handler/completion.rs
Updated the comment completion functionality to include schema URL generation based on the document's URI. This change allows for more dynamic and context-aware completions when using the comment directive.
=> feat: enhance comment completion with schema URL support

crates/tombi-diagnostic/Cargo.toml
`tower-lsp` was incorrectly specified as a feature, not an optional dependency.
=> fix: tombi-diagnostic lsp feature

.github/workflows/release_cli_vscode.yml, xtask/src/command/dist.rs
- Added a step to use rust-cache for caching Rust toolchain installations in the CI workflow.
- Modified the cargo build command to use the --locked flag for better dependency management.
=> ci: update rust toolchain installation step

crates/tombi-config/src/schema.rs, crates/tombi-config/src/types.rs, crates/tombi-config/src/types/schema_catalog_path.rs, crates/tombi-lsp/tests/completion_labels.rs, crates/tombi-lsp/tests/document_link.rs, docs/src/routes/docs/configuration/index.mdx, extensions/tombi-extension-tombi/src/document_link.rs, tombi.schema.json, tombi.toml
`schema.catalog.path` -> `schema.catalog.paths` in `tombi.toml`.
- Refactored schema catalog to use an array of paths instead of a single path.
- Updated related documentation and tests to reflect the new structure.
- Deprecated the old path field in favor of the new paths array.
=> feat: update schema catalog handling to support paths array

.github/workflows/release_cli_vscode.yml
Updated the timeout for the VSCode extension publishing step from 2 to 5 minutes to accommodate longer processing times.
=> ci: increase timeout for VSCode extension publishing

rust/tombi-cli/src/app/command/format.rs
Introduce an `always-output` option to allow users to output formatted TOML to stdout even when there are no changes, enhancing usability for standard input scenarios.
fix: #450
=> Add always-output option for TOML formatting

Cargo.lock, crates/tombi-json-arena/Cargo.toml, crates/tombi-json-arena/src/arena/object.rs, crates/tombi-json-arena/src/lib.rs
Updated the ObjectArena structure to use HashMap instead of IndexMap, improving memory efficiency for JSON Schema interpretation. Removed indexmap dependency from Cargo.toml.
=> refactor: replace IndexMap with HashMap for memory efficiency

.github/workflows/release_pypi.yml
The last [pre-commit mirror update](https://github.com/tombi-toml/tombi-pre-commit/actions/runs/15463061010) was triggered before the package was uploaded to pypi.
This ensures the motify step only run when the pypi upload is done.
=> Fix race condition with pypi release

crates/tombi-lsp/src/backend.rs, crates/tombi-lsp/src/goto_definition.rs, crates/tombi-schema-store/src/lib.rs, crates/tombi-schema-store/src/store.rs
Updated the schema fetching logic to use the new get_tombi_scheme_content function, improving code clarity and maintainability. Adjusted related usages in the LanguageServer implementation and the SchemaStore.
=> feat: replace get_tombi_github_schema_url with get_tombi_scheme_content

crates/tombi-schema-store/src/schema/source_schema.rs, tombi.toml
Updated the root_schema_url in SourceSchema's Debug implementation to return a string representation of the schema URL instead of a reference.
=> fix: update root_schema_url to return string representation

rust-toolchain.toml
Add a new rust-toolchain.toml file to specify the stable channel and include essential components like clippy, rust-analyzer, and rustfmt.
=> feat: add rust toolchain configuration file

.github/workflows/release_npm.yml
Reset TOMBI_VERSION to an empty string in the release_npm.yml workflow.
=> chore: clear TOMBI_VERSION in release workflow

crates/tombi-date-time/README.md
Add initial documentation for the tombi-date-time crate, including its basis on toml_datetime and details about the serialize method as a String NewType.
=> docs: add README for tombi-date-time crate

crates/tombi-lsp/tests/test_document_link.rs, extensions/tombi-extension-cargo/src/document_link.rs
Fix: https://github.com/tombi-toml/tombi/issues/544
- Implemented new tests for document links in the root package of a Cargo workspace.
- Enhanced the document link functionality to support links for dependencies defined in the root package.
=> feat: add document link tests for root package in Cargo.toml

crates/tombi-diagnostic/examples/diagnostics.rs, crates/tombi-diagnostic/src/lib.rs, crates/tombi-document-tree/src/error.rs, crates/tombi-linter/src/error.rs, crates/tombi-linter/src/linter.rs, crates/tombi-linter/src/severity.rs, crates/tombi-parser/src/error.rs, crates/tombi-schema-store/src/error.rs, crates/tombi-validator/src/error.rs, crates/tombi-validator/src/warning.rs
This commit introduces a `code` method for the `Error`, `Warning`, and `Severity` structs, allowing for more detailed diagnostics. The `Diagnostic` struct is updated to include a code parameter, enhancing error and warning messages with specific codes. This change improves the clarity and usability of diagnostics throughout the linter and validator components.
=> feat: add error and warning codes for diagnostics

Cargo.lock, rust/tombi-wasm/Cargo.toml, rust/tombi-wasm/src/lib.rs, rust/tombi-wasm/www/index.html
- Introduced a new `lint` function to perform linting on TOML files.
- Updated the HTML interface to include linting capabilities.
- Added `tombi-linter` as a workspace dependency.
- Modified the title and header in the HTML for better clarity.
=> feat: add linting functionality to tombi-wasm

rust/tombi-cli/src/app.rs
Updated the logging configuration to filter out logs from other crates, ensuring only relevant logs from the "tombi" target are displayed. This improves the clarity of log output during application runtime.
=> chore: enhance log filtering for better clarity

pyproject.toml
Fixes #729
Can confirm this sdist tarball builds successfully on Termux:
=> Include `schemas` dir in sdist

.github/workflows/ci_intellij_plugin.yml, DEVELOPMENT.md, editors/intellij/src/main/kotlin/tombi/server/TombiServerDescriptor.kt
Follow-up to #722.
This change adds a new workflow that will build the IntelliJ plugin, upload the artifacts and run its tests. This workflow is run on push (all changes) and pull request (only to related files).
=> feat: Build IntelliJ plugin on push and pull request

editors/zed/src/lib.rs
=> Revert "feat: zed plugin download file path incorrect"

json.schemastore.org/cargo.json
fix: https://github.com/tombi-toml/tombi/issues/1023
=> break: move "package" key order in `Cargo.toml`

Cargo.lock, Cargo.toml, crates/tombi-accessor/src/schema_accessor.rs, crates/tombi-diagnostic/Cargo.toml, crates/tombi-diagnostic/examples/diagnostics.rs, rust/tombi-cli/Cargo.toml, rust/tombi-cli/src/app.rs, rust/tombi-cli/src/app/options.rs, rust/tombi-cli/src/app/tracing_formatter.rs
Remove the quit option.
In practice, the quit option is never used, and it further interferes with the functionality of other options(like `--diff`) that output to the log.
=> feat: verbose flag.

Cargo.lock, Cargo.toml
Switching from `rustls-tls` to `rustls-tls-native-roots` in the `Cargo.toml` file fixes the issue I was facing in https://github.com/tombi-toml/tombi/issues/1035 because of a corp proxy that inspects traffic.
=> Adding `rustls-tls-native-roots` to utilise certificates in system truststores
